import Navbar from "../components/Navbar/Navbar";
import "../styles/globals.css";
import Head from "next/head";
import Radium, { StyleRoot } from "radium";

function MyApp({ Component, pageProps }) {
  return (
    <div>
      <StyleRoot>
        <Head>
          <title>Piyush Kumar Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/removedbg.png" />
        </Head>
        <div className="navbar" style={{ zIndex: "2" }}> 
          <Navbar />
        </div>
        <Component {...pageProps} />
      </StyleRoot>
    </div>
  );
}

export default Radium(MyApp);
