import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Main from '../components/Main/Main'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Piyush Kumar Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/removedbg.png" />
      </Head>
      <Main />
      
    </div>
  )
}
